version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - netlucas
    depends_on:
      db:
        condition: service_healthy
    container_name: service-node-expess
    restart: always
    tty: true

  db:
    command: --innodb-use-native-aio=0
    container_name: banco-de-dados
    restart: always
    tty: true
    build:
      context: .
      dockerfile: dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - netlucas
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "--user=root",
          "--password=${MYSQL_ROOT_PASSWORD}",
          "ping",
          "-h",
          "db",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:1.19
    container_name: service-nginx-proxy
    restart: always
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - netlucas
    
networks:
  netlucas:
    driver: bridge
